services:
  db:
    image: postgres:16-alpine
    container_name: task-app-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_db
    ports:
      - "5432:5432"
    volumes:
      - task-db-data:/var/lib/postgresql/data

  # アプリケーションの設定を追加
  app:
    build: .
    container_name: task-app-container
    ports:
      - "8085:8085" # application.yamlのserver.port(8085)に合わせる
    environment:
      # コンテナ間通信のためlocalhostをdb(サービス名)に変更
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/task_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: task-app-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  task-db-data: